= Table.AddColumn(#"Added Conditional Column2", "new_company", each if Text.Contains([company_Name], "Flint") then "Flint Group" else if Text.Contains([company_Name], "AdFarm ") then "AdFarm" else if Text.Contains([company_Name], "GiantGoat") or [Employee] = "Doug Foley" or [Employee] = "John Anderson"  or [Employee] = "Ben Mallory"  or [Employee] = "Nithya Harlor" or [Employee] = "Nithya Mani" then "Giant Goat" else if Text.Contains([company_Name], "Kahntact") and [Employee] <> "Doug Foley" and [Employee] <> "John Anderson"  and [Employee] <> "Ben Mallory"  and [Employee] <> "Nithya Harland" and [Employee] <> "Nithya Mani"  then "Kahntact" else if Text.Contains([company_Name], "Prime") then "Prime46" else if Text.Contains([company_Name], "Filter Marketing Inc.") then "AdFarm" else "Flint Group")