= Table.AddColumn(#"Added Conditional Column1", "new_team", each if Text.StartsWith([Team], "Digital") then "Digital46" else if Text.StartsWith([Team],"Media") and [Employee] <> "Kayla Roehrich" or [Employee] = "Michelle Clarke" then "Media46" else if [Team] = "Prime" then "Prime46" else if [Team] = "Super Studio" or [Employee] = "Wyatt Carlson" or [Employee] = "Kyle Schmidt" and  [Employee] <> "Nadja Jaspert" then "Studio46" else if [Team] = "Analytics" or [Employee] = "Kayla Roehrich"  then "Analytics46"
  else if [Team] = "Channel" or [Employee] = "Calista Liapis" then "Channel" else if Text.Contains([Team], "Creative") then "Manufacturing Creative Services (Creative)" else if [Team] = "Orange" 
  then "Orange" else if Text.Contains([Team], "PR & Social") or [Employee] = "Gavin Vink" or [Employee] = "Katherine Fearing" then "PR & Social" else if [Team] = "Professional Services" then "Professional Services" 
  else if [Team] = "Red" then "Red" else if [Team] = "AdFarm Canada" or [Employee] = "Aaron Crawford"  or [Employee] = "Ally Bosch" or [Employee] = "Amanda Howard" or [Employee] = "Andrea Dubak" 
  or [Employee] = "Audra Fimmers" or [Employee] = "Bridgette Ohrmund" or [Employee] = "Ben Graham" or [Employee] = "Bryce McKenzie" or [Employee] = "Connor Morrell" or [Employee] = "Diala Lada" 
  or [Employee] = "Erin Stadnicki" or [Employee] = "Glenn Dawes" or [Employee] = "Harley Hudon" or [Employee] = "Heidi Gammuac" or [Employee] = "Jenna Peacoc" or [Employee] = "Jennifer Oakes" or [Employee] = "Jessica Laidlaw-Richardson" 
  or [Employee] = "Kris Anderson" or [Employee] = "Mackenzie Argent" or [Employee] = "Mak Moore" or [Employee] = "Melissa Webster" or [Employee] = "Michelle Clayton" or [Employee] = "Michelle McIntyre" or [Employee] = "Moya Sharma" 
  or [Employee] = "Nadja Jasper" or [Employee] = "Nicole McAule" or [Employee] = "Paola Di Barbora" or [Employee] = "Patrice Fielding" or [Employee] = "Strathie Tompkins" or [Employee] = "Tracey Godi" 
  or [Employee] = "Virginia Harvey" then "AdFarm Canada" else if [Team] = "AdFarm USA"    or [Employee] = "Alison Rasmussen" or [Employee] = "Annie Hamilton" or [Employee] = "Bethany Karlberg" or [Employee] = "Brittnie Jimenez" 
  or [Employee] = "Carolynn Sinclair" or [Employee] = "Emily Monson"  or [Employee] = "Haley Mallory" or [Employee] = "Jami Felver" or [Employee] = "Jeremy Davis" or [Employee] = "Jessica Dammen" or [Employee] = "Jill Boland" or [Employee] = "Julia King" 
  or [Employee] = "Julie Warner" or [Employee] = "Kaylen Alexander" or [Employee] = "Les Kahl" or [Employee] = "Matt Weeks" or [Employee] = "Phil French" or [Employee] = "Rebekah Dykhuizen" or [Employee] = "Rosie Thoni" or [Employee] = "Sarah Malone" 
  or [Employee] = "Syvenna Siebert" then "AdFarm USA" else if [Team] = "New Business" and [Employee] <> "Carolynn Sinclair" and  [Employee] <> "Les Kahl" and  [Employee] <> "Doug Foley" then "New Business" else if [Team] = "AdFarm CDA" then "AdFarm Canada" else if [Team] = "Blue" then "Professional Services" else if [Team] = "Green" 
  then "Professional Services" else null)